#### In this notebook we are going to cover some of the most fundamental concepts of tensors using Tensorflow
More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function ( a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercise to try for myself.

#### Introduction to Tensors

In [1]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
# Creat tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimension)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension fo our vector
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[10, 7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number)

#### Creating tensors with 'tf.variable'

In [12]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# change values in the changeable_tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

#### v18 Creating Random Tensors

Random tensors are tensor of some arbitrary size that contain random numbers

In [14]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproductibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order

In [15]:
# Shuffle a tensor (valuable for you want to shuffle your data for make more precise the model)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
# Shuffle our tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [16]:
# Shuffle our tensor
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [17]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=23)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

Shuffle is very important so the model we are training gets the proper and complete info. So we can avoid that only one kind of info is passed through the model.

Global Level & Operational Level SEED give us aleways the same result.

#### Other ways to make tensors

In [18]:
#Creata a tensor all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [19]:
# Create a tensor of all zeros
tf.zeros([3,7])

<tf.Tensor: shape=(3, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

#### Turn numpy arrays into tensors

The main difference is that tensor can be run in GPU much faster

In [20]:
# You can also convert Numpy Arrarys into Tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a Numpy array between 1 and 25
numpy_A

# x = tf.constant(some_matrix) # capital for tensors
# y = tf.constant(vector) # non-capital for tensors

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [21]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [22]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

When reshaping, the shape number of the vector should be the product of the values of the dimensions

In [23]:
A.ndim

3

#### Getting info from the tensors (attributes)

* Shape
* Size
* Axis or Dimension
* Rank

In [24]:
# Create a rank 4 tensor (4 dimensions)

tf4_ranked = tf.zeros(shape=[2,3,4,5])
tf4_ranked

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
tf4_ranked[0,0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [26]:
tf.rank(tf4_ranked)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [27]:
tf4_ranked.shape, tf4_ranked.ndim,  tf.size(tf4_ranked)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [28]:
2*3*4*5

120

In [29]:
# Get various attributes of our tensor
print("Datatype of every element: ", tf4_ranked.dtype)
print("Number of dimensions (rank): ", tf4_ranked.ndim)
print("Shape of tensor: ", tf4_ranked.shape)
print("Elements along the 0 axis: ", tf4_ranked.shape[0])
print("Elements along the last axis: ", tf4_ranked.shape[-1])
print("Total number of elements in our tensor: ", tf.size(tf4_ranked).numpy())
print("Total number of elements in our tensor: ", tf.size(tf4_ranked))

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  120
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)


#### Indexing and Expanding

Tensor can indexed just like Python lists

In [30]:
# Get the first 2 elements of each dimension

tf4_ranked[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
# Get the first element of each index exccept of the last one
tf4_ranked[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
tf4_ranked[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [33]:
# Create a 2 dim tensor
tf2_ranked = tf.constant([[3,7],
                         [5,11]])
tf2_ranked.shape, tf2_ranked.ndim

(TensorShape([2, 2]), 2)

In [34]:
# Get the last item of each row
tf2_ranked[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 11], dtype=int32)>

In [35]:
# Add dimensions
tf3_ranked = tf2_ranked[..., tf.newaxis]
tf3_ranked

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 7]],

       [[ 5],
        [11]]], dtype=int32)>

In [36]:
tf3_ranked.shape, tf3_ranked.ndim, tf.size(tf3_ranked).numpy()

(TensorShape([2, 2, 1]), 3, 4)

In [37]:
tf.size(tf2_ranked).numpy()

4

We added a new axis (one more dimension) but the size don't change??

In [38]:
# Alternative to tf.newaxis

tf.expand_dims(tf2_ranked, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[ 3,  7]],

       [[ 5, 11]]], dtype=int32)>

In [39]:
tf.expand_dims(tf2_ranked, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 3],
        [ 7]],

       [[ 5],
        [11]]], dtype=int32)>

#### Manipulating Tensors (Tensors Operations)

**BASIC OPERATIONS**

In [40]:
# You can add values to a tensor using the addition operator

tensor = tf.constant ([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [41]:
# In the same way we can use basic opertaion llike +, -, *, /
# But when tensor are bigger built-in libraries tf.math works in a GPu mode much more faster

tf.multiply(tensor, 100)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1000,  700],
       [ 300,  400]], dtype=int32)>

In [42]:
# In this operation usually we need (or want) that the values of tensor remains unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**MATRIX MULTIPLICATION**

In machine learning, matrix multiplication is one of the most common tensor operations


In [43]:
tensor1 = tf.random.normal(shape=[3,2])
tensor2 = tf.random.normal(shape=[2,3])

tensor1, tensor2, tf.matmul(tensor1,tensor2)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.3274685, -0.8426258],
        [ 0.3194337, -1.4075519],
        [-2.3880599, -1.0392479]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.08422458, -0.86090374,  0.37812304],
        [-0.00519627, -0.49453196,  0.6178192 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.03195941,  0.13478652, -0.39676696],
        [ 0.0342182 ,  0.42107773, -0.74882734],
        [-0.19573313,  2.569831  , -1.5450478 ]], dtype=float32)>)

👉 **Resource:** Info and example of matrix multiplication https://www.mathisfun.com/algebra/matrix-multiplying.html

In [44]:
# Transpose is an important tool in order to reshape
tensor1, tf.transpose(tensor1)

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.3274685, -0.8426258],
        [ 0.3194337, -1.4075519],
        [-2.3880599, -1.0392479]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.3274685,  0.3194337, -2.3880599],
        [-0.8426258, -1.4075519, -1.0392479]], dtype=float32)>)

In [45]:
tf.matmul(tf.transpose(tensor1),tf.transpose(tensor2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.1504012 , -1.635061  ],
       [ 0.7478334 ,  0.05839062]], dtype=float32)>

**The dot product**

Matrix multiplication is also referred as dot product

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [46]:
#  If the matrix indexes are to good for the matrix multiply just reshape or transpose
# (It depends on comparing the two tensors)

#In this case the two tensor are correct. So we try the transposer dot multiply
tf.tensordot(tf.transpose(tensor1),tf.transpose(tensor2), axes=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.1504012 , -1.635061  ],
       [ 0.7478334 ,  0.05839062]], dtype=float32)>

In [47]:
tf.matmul(tf.transpose(tensor1),tf.reshape(tensor2, shape=(3,2)))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.329338  , -1.758968  ],
       [-0.08925635,  0.09066647]], dtype=float32)>

#### Change the data types of a tensor

In [48]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [49]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [50]:
# Change from float32 to float16 (reduce precision)
C = tf.cast(B, dtype=tf.float16)
C.dtype

tf.float16

In [51]:
 # Change from int32 to float32
 E = tf.cast(C, dtype=tf.float32)
 E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7001953, 7.3984375], dtype=float32)>

In [52]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

#### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [53]:
# Getting the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [54]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

The way through the following forms of aggregation:

- Get the minimun
- Get the maximun
- Get the mean of a tensor
- Get the sum of a tensor

In [61]:
# Create a (2,3,2) shape random normal tensor
ef_Tensor = tf.random.normal(shape=[2,3,2])
ef_Tensor

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[ 0.65648675, -0.4130517 ],
        [ 0.33997506, -1.0056272 ],
        [ 0.70266235, -1.4008642 ]],

       [[-0.89780754, -0.34856176],
        [-0.95890623,  1.1948482 ],
        [ 0.8507053 , -0.30878615]]], dtype=float32)>

In [62]:
MAX_E = tf.math.reduce_max(ef_Tensor)
MIN_E = tf.math.reduce_min(ef_Tensor)
print('Maximun: ',MAX_E)
print('Minimun: ',MIN_E)

Maximun:  tf.Tensor(1.1948482, shape=(), dtype=float32)
Minimun:  tf.Tensor(-1.4008642, shape=(), dtype=float32)


In [63]:
# We don't need to use math just tf.reduce_mean, tf.reduce_max, etc.
MEAN_E = tf.reduce_mean(ef_Tensor)
MEAN_E

<tf.Tensor: shape=(), dtype=float32, numpy=-0.1324106>

In [65]:
F = tf.constant(np.random.randint(0, 100, size=50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([80, 78, 56, 90, 47, 62, 66, 61, 38, 29,  2, 14, 46, 19,  1, 21, 21,
       61, 62, 84, 69, 49, 14, 59, 43, 14, 54, 89, 64, 27, 32, 43, 68, 16,
       13, 13, 11, 48,  5, 83, 12, 19, 52, 67, 20,  0, 74, 27, 51, 22])>

In [67]:
tf.size(F), F.shape, F.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [68]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [69]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=int64, numpy=90>

In [70]:
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=int64, numpy=41>

In [71]:
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2096>

⚒️ **Exercise**: Find the standard deviation and the variance using tensorflow methods

In [76]:
tf.math.reduce_variance(tf.cast(F, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=676.31366>

In [77]:
tf.math.reduce_std(tf.cast(F, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.006031>

In [78]:
import tensorflow_probability as tfp

In [80]:
tfp.stats.variance(F)

<tf.Tensor: shape=(), dtype=int64, numpy=677>

#### Find the positional maximun and minimun of a tensor