### 👉 **Exercises**

TensorFlow Fundamentals

1. Create a vector, a scalar, matrix and tensor with values of your choosing using `tf.constant()`. 🟦

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
# Create a vector
vector = tf.constant([2,3])
# Create a scalar
scalar = tf.constant([7])
# Create a matrix
matrix = tf.constant([[1,2,3],
                      [4,5,6]])
# Create a Tensor (all of the above are also tensors)
tensor = tf.constant([[[ 1., 2., 3.,],
                       [ 4., 5., 6.]],
                      [[ 7., 8., 9.],
                       [10.,11.,12.]]])
print('scalar: ',scalar)
print('vector: ',vector)
print('matrix: ',matrix)
print('tensor: ',tensor)

scalar:  tf.Tensor([7], shape=(1,), dtype=int32)
vector:  tf.Tensor([2 3], shape=(2,), dtype=int32)
matrix:  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tensor:  tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float32)


2. Find the shape, rank and size of the tensors you created in 1.

In [4]:
scalar.shape, tf.rank(scalar),tf.size(scalar)

(TensorShape([1]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [5]:
vector.shape, tf.rank(vector),tf.size(vector)

(TensorShape([2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [6]:
matrix.shape, tf.rank(matrix),tf.size(matrix)

(TensorShape([2, 3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [14]:
# Using .numpy() method to get only the value as you can compare with line upwards
tensor.shape, tf.rank(tensor).numpy(), tf.size(tensor).numpy()

(TensorShape([2, 2, 3]), 3, 12)

3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [15]:
random_tf1 = tf.random.uniform([5, 300], minval=0, maxval=1)
random_tf2 = tf.random.uniform([5, 300], minval=0, maxval=1)

print('First: ',random_tf1)
print('Second: ',random_tf2)

First:  tf.Tensor(
[[0.23594439 0.68206596 0.24659824 ... 0.7704028  0.47435224 0.3998351 ]
 [0.07791758 0.2539575  0.6690314  ... 0.36304688 0.44514036 0.34281933]
 [0.71617746 0.8323386  0.845857   ... 0.13135588 0.2931192  0.29930353]
 [0.75091004 0.11035311 0.48716605 ... 0.97100174 0.80669713 0.55957127]
 [0.89192915 0.47279298 0.36343277 ... 0.8886714  0.10069048 0.85792744]], shape=(5, 300), dtype=float32)
Second:  tf.Tensor(
[[0.76902044 0.98869014 0.0261085  ... 0.78599787 0.4298377  0.41492212]
 [0.41811705 0.15848279 0.6470711  ... 0.48870683 0.76578915 0.6975424 ]
 [0.5043664  0.80562484 0.7851857  ... 0.45496762 0.639223   0.52654684]
 [0.3901205  0.14298749 0.8614553  ... 0.9008043  0.5614488  0.02631128]
 [0.0896275  0.9506     0.75523007 ... 0.05860412 0.97493887 0.81157947]], shape=(5, 300), dtype=float32)


4. Multiply the two tensors you created in 3 using matrix multiplication.

In [17]:
tf.multiply(random_tf1,random_tf2)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.18144606, 0.6743519 , 0.00643831, ..., 0.605535  , 0.20389448,
        0.16590042],
       [0.03257867, 0.04024789, 0.4329109 , ..., 0.17742349, 0.34088367,
        0.23913103],
       [0.36121586, 0.6705526 , 0.6641548 , ..., 0.05976267, 0.18736853,
        0.15759733],
       [0.2929454 , 0.01577912, 0.41967177, ..., 0.87468255, 0.45291916,
        0.01472304],
       [0.07994138, 0.44943702, 0.27447537, ..., 0.05207981, 0.09816707,
        0.6962763 ]], dtype=float32)>