### 👉 **Exercises**

TensorFlow Fundamentals

1. Create a vector, a scalar, matrix and tensor with values of your choosing using `tf.constant()`. 🟦

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Create a vector
vector = tf.constant([2,3])
# Create a scalar
scalar = tf.constant([7])
# Create a matrix
matrix = tf.constant([[1,2,3],
                      [4,5,6]])
# Create a Tensor (all of the above are also tensors)
tensor = tf.constant([[[ 1., 2., 3.,],
                       [ 4., 5., 6.]],
                      [[ 7., 8., 9.],
                       [10.,11.,12.]]])
print('scalar: ',scalar)
print('vector: ',vector)
print('matrix: ',matrix)
print('tensor: ',tensor)

scalar:  tf.Tensor([7], shape=(1,), dtype=int32)
vector:  tf.Tensor([2 3], shape=(2,), dtype=int32)
matrix:  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tensor:  tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float32)


2. Find the shape, rank and size of the tensors you created in 1.

In [3]:
scalar.shape, tf.rank(scalar),tf.size(scalar)

(TensorShape([1]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [4]:
vector.shape, tf.rank(vector),tf.size(vector)

(TensorShape([2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [5]:
matrix.shape, tf.rank(matrix),tf.size(matrix)

(TensorShape([2, 3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [6]:
# Using .numpy() method to get only the value as you can compare with line upwards
tensor.shape, tf.rank(tensor).numpy(), tf.size(tensor).numpy()

(TensorShape([2, 2, 3]), 3, 12)

3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [7]:
random_tf1 = tf.random.uniform([5, 300], minval=0, maxval=1)
random_tf2 = tf.random.uniform([5, 300], minval=0, maxval=1)

print('First: ',random_tf1)
print('Second: ',random_tf2)

First:  tf.Tensor(
[[0.31786847 0.8738009  0.18357944 ... 0.8202224  0.01691341 0.5548605 ]
 [0.44880664 0.79212856 0.24210167 ... 0.40478134 0.10072112 0.28673506]
 [0.8210399  0.7331743  0.3540758  ... 0.14919364 0.3596977  0.870083  ]
 [0.7125579  0.82056355 0.37758398 ... 0.03545952 0.01544261 0.04051137]
 [0.81949186 0.50079536 0.22230506 ... 0.04253972 0.17731142 0.10872757]], shape=(5, 300), dtype=float32)
Second:  tf.Tensor(
[[0.28515017 0.10173309 0.43054533 ... 0.5817621  0.16215563 0.8058822 ]
 [0.14375162 0.9380406  0.5666696  ... 0.17869782 0.38910306 0.17810321]
 [0.9113138  0.9656571  0.93184364 ... 0.63692117 0.08158684 0.82303786]
 [0.24247122 0.7667482  0.19182754 ... 0.40663433 0.09384811 0.7019273 ]
 [0.37035203 0.9709015  0.6268095  ... 0.3937919  0.34403908 0.5404924 ]], shape=(5, 300), dtype=float32)


4. Multiply the two tensors you created in 3 using matrix multiplication.

In [8]:
tf.multiply(random_tf1,random_tf2)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.09064025, 0.08889446, 0.07903928, ..., 0.47717428, 0.00274261,
        0.4471522 ],
       [0.06451669, 0.7430488 , 0.13719165, ..., 0.07233354, 0.0391909 ,
        0.05106843],
       [0.748225  , 0.707995  , 0.32994327, ..., 0.09502459, 0.0293466 ,
        0.71611124],
       [0.17277479, 0.62916565, 0.07243101, ..., 0.01441906, 0.00144926,
        0.02843604],
       [0.30350047, 0.48622295, 0.13934292, ..., 0.0167518 , 0.06100206,
        0.05876643]], dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

In [9]:
random_tf1 * random_tf1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[1.0104036e-01, 7.6352799e-01, 3.3701412e-02, ..., 6.7276478e-01,
        2.8606359e-04, 3.0787015e-01],
       [2.0142740e-01, 6.2746763e-01, 5.8613218e-02, ..., 1.6384794e-01,
        1.0144744e-02, 8.2216993e-02],
       [6.7410654e-01, 5.3754461e-01, 1.2536967e-01, ..., 2.2258744e-02,
        1.2938243e-01, 7.5704437e-01],
       [5.0773877e-01, 6.7332453e-01, 1.4256966e-01, ..., 1.2573774e-03,
        2.3847420e-04, 1.6411711e-03],
       [6.7156690e-01, 2.5079599e-01, 4.9419541e-02, ..., 1.8096274e-03,
        3.1439342e-02, 1.1821685e-02]], dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [10]:
random_tf3 = tf.random.uniform([224,224,3], minval=0, maxval=1)
random_tf3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.33894002, 0.42895818, 0.9085665 ],
        [0.14473629, 0.47300434, 0.62246096],
        [0.96175027, 0.7444372 , 0.90824914],
        ...,
        [0.02926385, 0.26358104, 0.05244541],
        [0.32343578, 0.7668625 , 0.38921702],
        [0.4289074 , 0.88078046, 0.79652715]],

       [[0.79878354, 0.6306335 , 0.79635274],
        [0.5333772 , 0.41311514, 0.6722604 ],
        [0.18539047, 0.6215522 , 0.9189435 ],
        ...,
        [0.65804935, 0.50406325, 0.2479124 ],
        [0.5929513 , 0.65885377, 0.64551675],
        [0.6394713 , 0.5087664 , 0.5208088 ]],

       [[0.81968606, 0.3650174 , 0.3654636 ],
        [0.42147398, 0.18978155, 0.40341508],
        [0.19030619, 0.22254634, 0.9633279 ],
        ...,
        [0.84808576, 0.10551882, 0.42815638],
        [0.5192001 , 0.26861024, 0.39787686],
        [0.11531818, 0.8026848 , 0.6933565 ]],

       ...,

       [[0.01775205, 0.61381245, 0.9595088 ],
        [0.78

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [13]:
max7 = tf.math.reduce_max(random_tf3, axis=0)
max7

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.99681616, 0.99361765, 0.99810684],
       [0.9961717 , 0.9885204 , 0.9987328 ],
       [0.997465  , 0.99498177, 0.99893963],
       [0.99956024, 0.9977838 , 0.99719715],
       [0.9978609 , 0.9911014 , 0.9857172 ],
       [0.9890801 , 0.99768806, 0.99625444],
       [0.9980804 , 0.9933387 , 0.9963913 ],
       [0.99719524, 0.99992156, 0.99260163],
       [0.9997083 , 0.9986384 , 0.99044776],
       [0.993917  , 0.99950385, 0.99568534],
       [0.9999789 , 0.9952779 , 0.9974253 ],
       [0.99618924, 0.99480426, 0.99880695],
       [0.9983469 , 0.9984838 , 0.99488914],
       [0.99027336, 0.9834794 , 0.9943633 ],
       [0.99733436, 0.99624634, 0.9992933 ],
       [0.98948205, 0.9969821 , 0.9923086 ],
       [0.9918742 , 0.99963963, 0.9989686 ],
       [0.99359846, 0.9952234 , 0.9916725 ],
       [0.99836266, 0.9974786 , 0.9964626 ],
       [0.9897659 , 0.99969363, 0.9954417 ],
       [0.9975039 , 0.9978528 , 0.99908936],
     

In [14]:
min7 = tf.math.reduce_min(random_tf3, axis=0)
min7

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[1.04784966e-03, 2.45249271e-03, 6.62648678e-03],
       [4.02867794e-03, 2.32934952e-04, 2.20763683e-03],
       [8.65221024e-04, 6.58047199e-03, 1.41836405e-02],
       [7.56132603e-03, 4.98056412e-04, 4.12988663e-03],
       [3.23677063e-03, 5.31935692e-03, 9.85264778e-04],
       [7.14421272e-04, 1.00734234e-02, 1.45359039e-02],
       [1.38461590e-03, 2.96485424e-03, 5.68354130e-03],
       [1.78611279e-03, 1.07054710e-02, 9.37426090e-03],
       [8.10623169e-05, 3.87609005e-03, 1.54757500e-03],
       [5.38861752e-03, 1.53279305e-03, 4.58335876e-03],
       [6.32011890e-03, 1.60491467e-03, 1.94728374e-03],
       [8.72254372e-04, 1.77180767e-03, 1.64568424e-03],
       [3.52144241e-03, 2.69484520e-03, 1.62959099e-03],
       [2.14850903e-03, 1.05901957e-02, 2.68816948e-04],
       [5.29289246e-04, 6.77585602e-03, 6.09588623e-03],
       [6.90746307e-03, 1.19047165e-02, 2.82168388e-04],
       [1.18628740e-02, 1.87122822e-03

8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [15]:
random_tf4 = tf.random.uniform([1,224,224,3])
random_tf4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.10811472, 0.38620222, 0.67500687],
         [0.30562723, 0.85340464, 0.4200542 ],
         [0.5629655 , 0.1945523 , 0.5712091 ],
         ...,
         [0.6328951 , 0.17901897, 0.11174023],
         [0.29819977, 0.3407371 , 0.56668305],
         [0.33277977, 0.48666894, 0.38789105]],

        [[0.02191949, 0.10558724, 0.7771878 ],
         [0.8330021 , 0.71897066, 0.27334917],
         [0.4470321 , 0.63583636, 0.963454  ],
         ...,
         [0.59425175, 0.9638666 , 0.21546423],
         [0.18347299, 0.312891  , 0.51152813],
         [0.42437446, 0.6524373 , 0.933905  ]],

        [[0.81962276, 0.3609525 , 0.7345145 ],
         [0.01455855, 0.07699895, 0.79131615],
         [0.3770417 , 0.11514497, 0.89791155],
         ...,
         [0.50869966, 0.71694624, 0.43178988],
         [0.7531855 , 0.88621056, 0.7471262 ],
         [0.63234115, 0.45704615, 0.51419806]],

        ...,

        [[0.7680757 , 0.79618144, 

In [16]:
tf4_squeezed = tf.squeeze(random_tf4)
tf4_squeezed

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.10811472, 0.38620222, 0.67500687],
        [0.30562723, 0.85340464, 0.4200542 ],
        [0.5629655 , 0.1945523 , 0.5712091 ],
        ...,
        [0.6328951 , 0.17901897, 0.11174023],
        [0.29819977, 0.3407371 , 0.56668305],
        [0.33277977, 0.48666894, 0.38789105]],

       [[0.02191949, 0.10558724, 0.7771878 ],
        [0.8330021 , 0.71897066, 0.27334917],
        [0.4470321 , 0.63583636, 0.963454  ],
        ...,
        [0.59425175, 0.9638666 , 0.21546423],
        [0.18347299, 0.312891  , 0.51152813],
        [0.42437446, 0.6524373 , 0.933905  ]],

       [[0.81962276, 0.3609525 , 0.7345145 ],
        [0.01455855, 0.07699895, 0.79131615],
        [0.3770417 , 0.11514497, 0.89791155],
        ...,
        [0.50869966, 0.71694624, 0.43178988],
        [0.7531855 , 0.88621056, 0.7471262 ],
        [0.63234115, 0.45704615, 0.51419806]],

       ...,

       [[0.7680757 , 0.79618144, 0.07560587],
        [0.87

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [17]:
random_tf5 = tf.constant(np.random.randint(0, 100, size=10))
random_tf5

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([66, 70, 18, 33, 11,  0, 37, 66, 92, 64])>

10. One-hot encode the tensor you created in 9.

In [19]:
tf.one_hot(random_tf5, depth=1)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>