### 👉 **Exercises**

TensorFlow Fundamentals

1. Create a vector, a scalar, matrix and tensor with values of your choosing using `tf.constant()`. 🟦

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
# Create a vector
vector = tf.constant([2,3])
# Create a scalar
scalar = tf.constant([7])
# Create a matrix
matrix = tf.constant([[1,2,3],
                      [4,5,6]])
# Create a Tensor (all of the above are also tensors)
tensor = tf.constant([[[ 1., 2., 3.,],
                       [ 4., 5., 6.]],
                      [[ 7., 8., 9.],
                       [10.,11.,12.]]])
print('scalar: ',scalar)
print('vector: ',vector)
print('matrix: ',matrix)
print('tensor: ',tensor)

scalar:  tf.Tensor([7], shape=(1,), dtype=int32)
vector:  tf.Tensor([2 3], shape=(2,), dtype=int32)
matrix:  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tensor:  tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float32)


2. Find the shape, rank and size of the tensors you created in 1.

In [4]:
scalar.shape, tf.rank(scalar),tf.size(scalar)

(TensorShape([1]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [5]:
vector.shape, tf.rank(vector),tf.size(vector)

(TensorShape([2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [6]:
matrix.shape, tf.rank(matrix),tf.size(matrix)

(TensorShape([2, 3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [14]:
# Using .numpy() method to get only the value as you can compare with line upwards
tensor.shape, tf.rank(tensor).numpy(), tf.size(tensor).numpy()

(TensorShape([2, 2, 3]), 3, 12)