### 👉 **Exercises**

TensorFlow Fundamentals

1. Create a vector, a scalar, matrix and tensor with values of your choosing using `tf.constant()`. 🟦

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Create a vector
vector = tf.constant([2,3])
# Create a scalar
scalar = tf.constant([7])
# Create a matrix
matrix = tf.constant([[1,2,3],
                      [4,5,6]])
# Create a Tensor (all of the above are also tensors)
tensor = tf.constant([[[ 1., 2., 3.,],
                       [ 4., 5., 6.]],
                      [[ 7., 8., 9.],
                       [10.,11.,12.]]])
print('scalar: ',scalar)
print('vector: ',vector)
print('matrix: ',matrix)
print('tensor: ',tensor)

scalar:  tf.Tensor([7], shape=(1,), dtype=int32)
vector:  tf.Tensor([2 3], shape=(2,), dtype=int32)
matrix:  tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tensor:  tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float32)


2. Find the shape, rank and size of the tensors you created in 1.

In [3]:
scalar.shape, tf.rank(scalar),tf.size(scalar)

(TensorShape([1]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [4]:
vector.shape, tf.rank(vector),tf.size(vector)

(TensorShape([2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [5]:
matrix.shape, tf.rank(matrix),tf.size(matrix)

(TensorShape([2, 3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [6]:
# Using .numpy() method to get only the value as you can compare with line upwards
tensor.shape, tf.rank(tensor).numpy(), tf.size(tensor).numpy()

(TensorShape([2, 2, 3]), 3, 12)

3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [7]:
random_tf1 = tf.random.uniform([5, 300], minval=0, maxval=1)
random_tf2 = tf.random.uniform([5, 300], minval=0, maxval=1)

print('First: ',random_tf1)
print('Second: ',random_tf2)

First:  tf.Tensor(
[[0.9359535  0.59872115 0.0610292  ... 0.05917025 0.98390436 0.17248428]
 [0.44957507 0.98012114 0.4079783  ... 0.27560723 0.7758063  0.9390229 ]
 [0.24058771 0.7274393  0.62350726 ... 0.496153   0.78254426 0.48540998]
 [0.9048027  0.6411536  0.46212244 ... 0.37833667 0.64652026 0.83549404]
 [0.9635532  0.11608422 0.94470763 ... 0.9471998  0.8801757  0.28581083]], shape=(5, 300), dtype=float32)
Second:  tf.Tensor(
[[0.4175117  0.67981255 0.8995606  ... 0.934885   0.3821324  0.8402381 ]
 [0.85889554 0.36154294 0.75499165 ... 0.48482168 0.33022487 0.9306141 ]
 [0.9586561  0.3334992  0.16488695 ... 0.74446344 0.60196316 0.7698616 ]
 [0.02768707 0.5892303  0.06661916 ... 0.18987584 0.6710856  0.12275302]
 [0.20914567 0.17858243 0.18756688 ... 0.8119774  0.16215742 0.8105302 ]], shape=(5, 300), dtype=float32)


4. Multiply the two tensors you created in 3 using matrix multiplication.

In [8]:
tf.multiply(random_tf1,random_tf2)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.39077154, 0.40701815, 0.05489946, ..., 0.05531738, 0.37598175,
        0.14492786],
       [0.38613802, 0.35435587, 0.3080202 , ..., 0.13362035, 0.25619054,
        0.873868  ],
       [0.23064087, 0.24260041, 0.10280821, ..., 0.36936778, 0.4710628 ,
        0.3736985 ],
       [0.02505134, 0.3777871 , 0.03078621, ..., 0.07183699, 0.43387043,
        0.10255942],
       [0.20152298, 0.0207306 , 0.17719586, ..., 0.76910484, 0.14272702,
        0.23165831]], dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

In [20]:
tf.tensordot(random_tf1, tf.transpose(random_tf2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.69414 , 76.37303 , 82.16891 , 74.27013 , 72.838356],
       [73.96456 , 72.78266 , 77.167046, 72.90436 , 69.12662 ],
       [75.59735 , 74.108986, 81.843   , 73.132   , 73.694954],
       [72.63776 , 73.90672 , 81.0436  , 72.06579 , 72.133545],
       [74.4572  , 73.52467 , 79.7126  , 73.57991 , 70.90101 ]],
      dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [10]:
random_tf3 = tf.random.uniform([224,224,3], minval=0, maxval=1)
random_tf3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[5.4685986e-01, 6.1394882e-01, 1.4676285e-01],
        [9.2716503e-01, 5.2784503e-01, 9.4844985e-01],
        [2.0004249e-01, 4.1791594e-01, 5.6143892e-01],
        ...,
        [4.6777725e-03, 4.4869149e-01, 2.5939476e-01],
        [8.8595927e-01, 9.3680227e-01, 9.0223360e-01],
        [7.3638797e-02, 6.4166439e-01, 9.9463665e-01]],

       [[1.6535509e-01, 5.1011419e-01, 1.5679908e-01],
        [9.5862234e-01, 5.1737428e-02, 7.2760057e-01],
        [2.5722861e-01, 6.4820659e-01, 3.8893914e-01],
        ...,
        [2.4498403e-01, 9.4239008e-01, 5.9563982e-01],
        [8.3284438e-01, 3.6107457e-01, 5.8256686e-01],
        [3.2573187e-01, 7.4192047e-01, 4.8510456e-01]],

       [[2.1345294e-01, 9.5550025e-01, 4.7143281e-01],
        [1.9749820e-01, 6.8737268e-03, 8.4215045e-02],
        [1.9183886e-01, 5.0890100e-01, 9.6007025e-01],
        ...,
        [6.8397605e-01, 1.8673491e-01, 1.2161732e-01],
        [4.3573093e-01

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [11]:
max7 = tf.math.reduce_max(random_tf3, axis=0)
max7

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.9986974 , 0.98460615, 0.99296236],
       [0.9990063 , 0.99821126, 0.98602164],
       [0.9995241 , 0.9946761 , 0.9989778 ],
       [0.9922395 , 0.99838483, 0.99310815],
       [0.99754894, 0.9943377 , 0.9970336 ],
       [0.999941  , 0.990335  , 0.99998915],
       [0.9912516 , 0.99556506, 0.9972341 ],
       [0.9982979 , 0.9838002 , 0.9921113 ],
       [0.99909997, 0.9946692 , 0.9996443 ],
       [0.99444246, 0.99958336, 0.99948955],
       [0.99837065, 0.9866257 , 0.9991381 ],
       [0.9953959 , 0.98245835, 0.9910538 ],
       [0.99577355, 0.9963882 , 0.99954855],
       [0.99626386, 0.9899043 , 0.9999325 ],
       [0.9999294 , 0.9978832 , 0.9963628 ],
       [0.99905944, 0.9993253 , 0.99631894],
       [0.99838674, 0.99014676, 0.9971769 ],
       [0.9979497 , 0.99750614, 0.99913716],
       [0.99526024, 0.9996594 , 0.9950391 ],
       [0.9928299 , 0.9919586 , 0.9921657 ],
       [0.9998317 , 0.9933411 , 0.9928826 ],
     

In [12]:
min7 = tf.math.reduce_min(random_tf3, axis=0)
min7

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[8.54611397e-04, 1.51872635e-04, 3.13150883e-03],
       [2.46634483e-02, 6.87372684e-03, 1.51956081e-03],
       [2.13527679e-03, 1.03235245e-04, 6.28852844e-03],
       [2.64406204e-04, 3.54433060e-03, 6.40058517e-03],
       [5.79833984e-04, 8.23140144e-03, 1.05350018e-02],
       [2.55537033e-03, 1.61578655e-02, 5.60879707e-04],
       [1.02269650e-03, 9.36150551e-04, 2.88176537e-03],
       [3.19349766e-03, 1.21461153e-02, 3.38470936e-03],
       [4.04703617e-03, 4.59802151e-03, 2.15566158e-03],
       [3.17037106e-03, 5.09810448e-03, 3.36563587e-03],
       [4.69684601e-04, 2.46524811e-04, 5.02324104e-03],
       [1.69959068e-02, 3.51107121e-03, 1.22964382e-03],
       [1.16014481e-03, 6.29162788e-03, 4.11748886e-04],
       [9.91821289e-05, 7.34686852e-04, 2.57396698e-03],
       [4.13262844e-03, 1.45971775e-03, 6.87944889e-03],
       [4.24289703e-03, 2.77900696e-03, 7.90822506e-03],
       [4.01854515e-04, 4.22620773e-03

8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [13]:
random_tf4 = tf.random.uniform([1,224,224,3])
random_tf4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.16137218, 0.00560784, 0.7429452 ],
         [0.9952055 , 0.714656  , 0.7082323 ],
         [0.74004555, 0.61647594, 0.5016581 ],
         ...,
         [0.73071635, 0.97248054, 0.00844932],
         [0.971336  , 0.53426456, 0.4858917 ],
         [0.6475308 , 0.52744806, 0.566102  ]],

        [[0.5695412 , 0.47327268, 0.3717736 ],
         [0.42460227, 0.41159236, 0.7895522 ],
         [0.649917  , 0.06454206, 0.20465708],
         ...,
         [0.4247291 , 0.64464104, 0.33240938],
         [0.6433326 , 0.4939332 , 0.49421597],
         [0.04554677, 0.349604  , 0.7966795 ]],

        [[0.8839601 , 0.93170846, 0.8368554 ],
         [0.2399683 , 0.9918598 , 0.74623454],
         [0.65495276, 0.048401  , 0.51385665],
         ...,
         [0.6819066 , 0.41743004, 0.2406373 ],
         [0.3473165 , 0.8819568 , 0.7537097 ],
         [0.86395144, 0.23371136, 0.5846696 ]],

        ...,

        [[0.83178043, 0.4219923 , 

In [14]:
tf4_squeezed = tf.squeeze(random_tf4)
tf4_squeezed

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.16137218, 0.00560784, 0.7429452 ],
        [0.9952055 , 0.714656  , 0.7082323 ],
        [0.74004555, 0.61647594, 0.5016581 ],
        ...,
        [0.73071635, 0.97248054, 0.00844932],
        [0.971336  , 0.53426456, 0.4858917 ],
        [0.6475308 , 0.52744806, 0.566102  ]],

       [[0.5695412 , 0.47327268, 0.3717736 ],
        [0.42460227, 0.41159236, 0.7895522 ],
        [0.649917  , 0.06454206, 0.20465708],
        ...,
        [0.4247291 , 0.64464104, 0.33240938],
        [0.6433326 , 0.4939332 , 0.49421597],
        [0.04554677, 0.349604  , 0.7966795 ]],

       [[0.8839601 , 0.93170846, 0.8368554 ],
        [0.2399683 , 0.9918598 , 0.74623454],
        [0.65495276, 0.048401  , 0.51385665],
        ...,
        [0.6819066 , 0.41743004, 0.2406373 ],
        [0.3473165 , 0.8819568 , 0.7537097 ],
        [0.86395144, 0.23371136, 0.5846696 ]],

       ...,

       [[0.83178043, 0.4219923 , 0.38993084],
        [0.54

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [15]:
random_tf5 = tf.constant(np.random.randint(0, 100, size=10))
random_tf5

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([38, 42, 22, 25, 17, 69, 98, 47, 91, 42])>

10. One-hot encode the tensor you created in 9.

In [16]:
tf.one_hot(random_tf5, depth=1)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>